local util = require "libs.opentrace.util"

local print = print

if ngx then
    print = ngx.print
end

local function from_hex_number(str)
    return (str:gsub('..', function (cc)
        return string.char(tonumber(cc, 16) or 0)
    end))
end

local s = "10.20.23.5"
print(string.gsub(s, "%D", ""))

local tab = {"424", 34, true, "4455"}
print(table.concat(tab, ","))

-- local num = tonumber("7a9ec9af6d5991e8", 16)
-- print(num)
-- print(string.format("%016x", num))
-- print("get_timestamp_now:", util.get_timestamp_now())
-- print("GeServiceName:", util.GeServiceName())
-- print("GetLocalIP:", util.GetLocalIP())
-- print("GenerateSpanID:", util.GenerateSpanID())
-- print("GenerateTraceID:",util.GenerateTraceID())
-- print("GetPort:", util.GetPort())

-- math.randomseed(os.time())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())

-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())
-- print("random:", math.random())